# _config-examples/multi-stage/github.yml

name: Docker Build

on: [push]

env:
    CACHE_IMAGE: mjhea0/docker-ci-cache
    MY_IMAGE: drivelous/docker-ci-cache
    DOCKER_BUILDKIT: 1

jobs:
    build:
        name: Build Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout master
              uses: actions/checkout@v1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ secrets.GHCR_USERNAME }}
                  password: ${{ secrets.GHCR_TOKEN }}

            - name: Build base from dockerfile
              run: |
                  docker build \
                      --target base \
                      --cache-from $CACHE_IMAGE:base \
                      --tag $MY_IMAGE:base \
                      --file ./Dockerfile.multi \
                      --build-arg BUILDKIT_INLINE_CACHE=1 \
                      "."

            - name: Build stage from dockerfile
              run: |
                  docker build \
                      --cache-from $CACHE_IMAGE:base \
                      --cache-from $CACHE_IMAGE:stage \
                      --tag $MY_IMAGE:stage \
                      --file ./Dockerfile.multi \
                      --build-arg BUILDKIT_INLINE_CACHE=1 \
                      "."

            - name: Push base image to docker hub
              run: docker push $MY_IMAGE:base

            - name: Push stage image to docker hub
              run: docker push $MY_IMAGE:stage
